name: gamieden
description: "Your game wishlist."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  bloc: ^9.0.0
  equatable: ^2.0.7
  hydrated_bloc: ^10.0.0
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  http: ^1.3.0
  path_provider: ^2.1.5
  steamstore_repository:
    path: packages/steamstore_repository
  nintendo_eshop_repository:
    path: packages/nintendo_eshop_repository
  local_storage_games_api:
    path: packages/local_storage_games_api
  games_api:
    path: packages/games_api
  games_repository:
    path: packages/games_repository
  beamer: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  mocktail: ^1.0.4
  # mocktail_image_network: ^1.2.0
  test: ^1.25.15

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_burr.jpeg
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
